name: Test & coverage

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set Yarn Version
        run: corepack prepare yarn@4.7.0 --activate
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: ./yarn.lock 
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: yarn build
      

